# Generated by Django 3.2.9 on 2021-11-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesupload',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='filesupload',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
